# Generated by Django 3.2 on 2021-04-24 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryLocation',
            field=models.IntegerField(choices=[(0, 'Inside of Dhaka'), (1, 'Division of Dhaka'), (2, 'Outside of Dhaka')], max_length=22),
        ),
    ]
