# Generated by Django 3.2 on 2021-04-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0002_alter_order_deliverylocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryLocation',
            field=models.IntegerField(choices=[(0, 'Inside of Dhaka'), (1, 'Division of Dhaka'), (2, 'Outside of Dhaka')]),
        ),
    ]
